# Configuration PostgreSQL (Docker)
db.url=jdbc:postgresql://localhost:5432/postgres
db.user=postgres
db.password=monmotdepasse

# Configuration des dossiers du batch
batch.dossier.source=C:/batch/input/
batch.dossier.archive=C:/batch/archive/